### PR TITLE
Add InnerException to ErrorInfo proposal

### PR DESCRIPTION
**Pull request by withakay**
This is a proposal for an improvement to ErrorInfo.

I have added an InnerException property to the ErrorInfo class for situations when an ErrorInfo is created from an Exception this can be assigned, hopefully making it easier to track down issues.

I have  have also updated AuthURL error handling to make use of the InnerException property and added a test to demonstrate it, this in in response to issue #325

### CODE REVIEW

**Comment by withakay** [comment]
`ErrorInfo` could inherit from `Exception` and then we down cast the `innerException` to an `ErrorInfo` and assign it to `cause` (well, `Cause` in c#), technically I think that would work (although iirc there might be some edge cases around serialisation I would have to double check). 

Semantically though, it *might* be a little odd as `ErrorInfo` is now an `Exception` sub class that never gets thrown and we already have `AblyException` for actually throwing Exceptions. 🤷‍♂

**Comment by mattheworiordan** [comment]
> Semantically though, it might be a little odd as ErrorInfo is now an Exception sub class that never gets thrown and we already have AblyException for actually throwing Exceptions. 

Well not sure what's best to be honest.  Feels like you need to work out what is best for C# and our SDK, and something we're willing to sticky by moving forwards.

**Comment by withakay** [comment]
@mattheworiordan 

I think `ErrorInfo` should not inherit from `Exception`, we should a `Cause` property of type `ErrorInfo` per the spec and where useful add another property to hold a reference to a 'source' `Exception`. I am not sure what the most appropriate name for that property would be though...

**Comment by withakay** [comment]
@mattheworiordan 
> what needs to change to a) ensure the cause and inner exception are used

I think it is a case of manually updating the code in the places where it is relevant. I would think we need to decide if that is a proactive or reactive process.

> b) is this definitely visible in logs sent to STDOUT? Do we, for example, need to define a serializer that ensures when this ErrorInfo is shown it includes that info?

Good catch. I have pushed a commit to address this, see https://github.com/ably/ably-dotnet/pull/328/commits/3255a1bf25cd1610592f4883231a0149412d7214

**Pull request merged**
