### PR TITLE
Use MSGPACK compiler flag to add/remove Protocol.MsgPack

### PR DESCRIPTION
**Pull request by withakay**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@withakay unfortunately a customer Casey has had an issue with this build.  He has an issue connecting, whereas the reconnect works.  I will send you the confidential info showing the problem now for you to review.

**Comment by withakay** [comment]
@mattheworiordan are you sure it is this branch and not what is in master?

**Comment by mattheworiordan** [comment]
@withakay given the customer has not been forthcoming with logs after almost two weeks now, I think we should aim to release this.  WDYT @withakay?

**Comment by withakay** [comment]
@mattheworiordan agreed, but perhaps lead with a beta release and give that a week or 2 before pushing a stable package?

**Comment by mattheworiordan** [comment]
> but perhaps lead with a beta release and give that a week or 2 before pushing a stable package?

Ok, perhaps once we have stabilised presence we can do a stable release. WDYT?

**Pull request merged**
