### PR TITLE
Token authentication for Realtime client

### PR DESCRIPTION
**Pull request by yavor87**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Nice work @yavor87, quality code as ever.

**Comment by yavor87** [comment]
Any other comments or notes? If not, can we merge this PR?

**Comment by mattheworiordan** [comment]
Merge away, :+1: . Do you want me to merge?

**Comment by yavor87** [comment]
Did you check my last commit on time()? I made it async as we discussed

**Pull request merged**
