### PR TITLE
Fix delay in initial presence sync

### PR DESCRIPTION
**Pull request by ashikns**
This fixes the delay caused due to WaitForSyncAsync not picking up sync complete the first time, described in issue https://github.com/ably/ably-dotnet/issues/204

### CODE REVIEW

**Comment by withakay** [comment]
Looks good to me 👍 

A note to other the reviewers: CI checks don't seem to be running for PRs from other repositories (which I will look into when I can). In the mean time I have cloned @ashikns repo and ran the tests locally, without issue.

**Comment by paddybyers** [comment]
This looks OK to me, but in all the other PresenceMap implementations there's just a single member that indicates that a sync is in progress (eg https://github.com/ably/ably-java/blob/develop/lib/src/main/java/io/ably/lib/realtime/Presence.java#L1013). Why in this case do we need two members (`_isSyncInProgress`, `_initialSyncCompleted`) ? I don't see why we can't replicate the functionality without having both.

**Comment by ashikns** [comment]
You could technically fix this by setting _InitialSyncCompleted = true;_ earlier, for example inside the try block. It would be lesser code, but it looked kinda odd to me and in the end I just decided to mirror code in the parent class.

**Comment by withakay** [comment]
@paddybyers 

> I don't see why we can't replicate the functionality without having both.

You are probably right, the `InitialSyncCompleted` parts were added by myself when I added WaitForSyncAsync(), refactoring those parts is probably beyond the scope of this PR. I could add a new issue to look at cleaning up the PresenceMap implementation at late date, WDYT?

**Comment by paddybyers** [comment]
> I could add a new issue to look at cleaning up the PresenceMap implementation at late date, WDYT?

I'm ok with that; @withakay ?

Thanks

**Comment by withakay** [comment]
@paddybyers I made a new issue to look at the PresenceMap implementation, are you now okay to approve this PR?

**Comment by paddybyers** [comment]
> are you now okay to approve this PR?

yes, thanks

**Pull request merged**
