### PR TITLE
Handle connectivity event

### LINKED ISSUE #1218: Implement RTN20C: Handle os connectivity event while `CONNECTING`
See https://github.com/ably/specification/pull/135 and [RTN20c](https://sdk.ably.com/builds/ably/specification/main/features/#RTN20c)

> When `CONNECTING`, if the operating system indicates that the underlying internet connection is now available, the client should restart the pending connection attempt

As part of this work, we should also ensure that RTN20a and RTN20c are implemented correctly. Also, "Connection: Handle OS connectivity events" should be added to the `features.yml` file.

### PR DESCRIPTION
**Pull request by sacOO7**
- Fixed #1218

### CODE REVIEW

**Comment by sacOO7** [comment]
The implementation shows a lot of flakiness in tests. Need to adjust it a bit, or implement a natural flow,

**Comment by sacOO7** [comment]
> The implementation shows a lot of flakiness in tests. Need to adjust it a bit, or implement a natural flow,

This has been fixed with a simple implementation of triggering `ConnectingStateCommand`.

**Review by marto83 — APPROVED** [review]
Nice. Looks good 👍🏼

**Review by owenpearson — APPROVED** [review]

**Comment by sacOO7** [comment]
Thanks for approval, merging the PR : )

**Pull request merged**
