### PR TITLE
Portable libs

### PR DESCRIPTION
**Pull request by Const-me**
Acceptance tests now pass on my machine

### CODE REVIEW

**Comment by Const-me** [comment]
All unit tests now pass.
At least when launching them with the new console runner application.

**Comment by mattheworiordan** [comment]
@Const-me this looks amazing, this is REALLY good work :+1:

**Comment by mattheworiordan** [comment]
Feel free to respond to my comments if you want, and confirm when you are happy for me to merge this work in to `master`

**Comment by Const-me** [comment]
> Any reason for committed commented code?
Unit tests serve many use cases. 1. Verify they all work 2. Identify which one fails. 3. Re-run the test that fail, possibly using debugger. That’s what commented code does in Ably.ConsoleTest\Program.cs

**Comment by Const-me** [comment]
> you are providing a  MessagePackMember  index here, what is this used for?

Not currently used.

**Comment by Const-me** [comment]
> update the README soon with instructions on how to run the test suite

OK, however it’s really simple now: build and run the command-line app.

**Comment by Const-me** [comment]
> Why did you remove Timeout ?

Not portable. There’s no Timeout value on each supported platform.
For portable library, it’s the compiler who now enforces such things.

**Comment by Const-me** [comment]
> can you explain so that I understand i.e. why have you introduced XUnit?

In your code base, both XUnit and NUnit framework were used for tests, one in Ably.AcceptanceTests another one in Ably.Tests. Because I wanted to run them all, I had to reference and use both frameworks.

**Comment by mattheworiordan** [comment]
>> Any reason for committed commented code?

> Unit tests serve many use cases. 1. Verify they all work 2. Identify which one fails. 3. Re-run the test that fail, possibly using debugger. That’s what commented code does in Ably.ConsoleTest\Program.cs

Yes, I love unit tests, but I was not sure why you are commenting out code that is not used and then committing to the repo. Why bloat the files with unused code?  Also, see an example like https://github.com/Const-me/ably-dotnet/commit/f8b213d32f9666bc2bd980b894ee6b58c962e49a#diff-40c7cb400eea73442b939c8323dba9f9R32, why is that commented out and committed?

>> update the README soon with instructions on how to run the test suite

> OK, however it’s really simple now: build and run the command-line app.

Fine, but we need to update the README still, even if easy, because easy for one person is not always obviously easy for another.  We're aiming to make things easy for our developers, that is one of our goals, so this is really important.

>> Why did you remove Timeout ?

> For portable library, it’s the compiler who now enforces such things.

How can a compiler enforce anything to do with an HTTP timeout? I am not following what you mean.

**Comment by Const-me** [comment]
Any reason for committed commented code?

Unit tests serve many use cases. 1. Verify they all work 2. Identify which one fails. 3. Re-run the test that fail, possibly using debugger. That’s what commented code does in Ably.ConsoleTest\Program.cs

Yes, I love unit tests, but I was not sure why you are commenting out code that is not used and then committing to the repo. Why bloat the files with unused code? Also, see an example like Const-me@ <https://github.com/Const-me/ably-dotnet/commit/f8b213d32f9666bc2bd980b894ee6b58c962e49a#diff-40c7cb400eea73442b939c8323dba9f9R32> f8b213d#diff-40c7cb400eea73442b939c8323dba9f9R32, why is that commented out and committed?

Because #1, #2 and #3 require different functionality from unit tests system.

For #1, you want to run them all with minimal output, because with full output important information for #1 which is “123 passed, 23 failed” will be lost).

For #2 you want to run them all, with full output.

For #3 you want to run a single test, and also you want it to throw exceptions when it failed.

That commented code switches between those use-cases.

And because previous developers picked two distinct unit testing framework for different tests, that code needs to be repeated for both frameworks.

If I’ll remove the commented code, it’ll be much harder to re-run a failed test.

 

Remember that whole utility, Ably.ConsoleTest, is targeted toward library developers, not library users.

I don’t see why not offer those developers to comment/uncomment a line of code, instead of reading the damn manual to find out which command-line arguments to supply to achieve the same effect.

 

update the README soon with instructions on how to run the test suite

OK, however it’s really simple now: build and run the command-line app.

Fine, but we need to update the README still, even if easy, because easy for one person is not always obviously easy for another. We're aiming to make things easy for our developers, that is one of our goals, so this is really important.

OK will do soon.

Why did you remove Timeout ?

For portable library, it’s the compiler who now enforces such things.

How can a compiler enforce anything to do with an HTTP timeout? I am not following what you mean.

When used correctly, a good compiler can verify a lot of different things.

The best thing is, unlike failed unit test that’s easy to ignore, you can’t ignore the output of compiler if it refuses to build your code.

In this case, the compiler has found out that some enum value isn’t universally available across the target platforms. It’s present in some platforms, but missing in others (probably ‘coz HTTP timeouts aren’t implemented on them). And because the output is now portable library, it just didn’t compile.

**Comment by mattheworiordan** [comment]
Ok fine re: comments, I understand the context.

Thanks re: README

Re: HTTP timeout, unfortunately it worries me that if some platforms do support Timeout, and some don't, then on the platforms that do that we are supporting, will we not be catching Timeout errors?

**Pull request merged**
