### PR TITLE
Release/1.2.13 - Upgrade to protocol 2.0

### PR DESCRIPTION
**Pull request by sacOO7**
Implement no-connection-serial

### CODE REVIEW

**Review by ttypic — APPROVED** [review]
LGTM

**Comment by owenpearson** [comment]
@sacOO7 I'm a bit confused by this - the name of the integration/2.0 branch/pr implies that we were releasing this as version 2.0? If there's no breaking changes then at the very least we should update the changelog and PR name to reflect that it's no longer a 2.0 change, but it looks like there are some breaking changes here so I think we need to have a discussion about whether it's appropriate to release this in a patch version

**Comment by sacOO7** [comment]
> @sacOO7 I'm a bit confused by this - the name of the integration/2.0 branch/pr implies that we were releasing this as version 2.0? If there's no breaking changes then at the very least we should update the changelog and PR name to reflect that it's no longer a 2.0 change, but it looks like there are some breaking changes here so I think we need to have a discussion about whether it's appropriate to release this in a patch version

Though, we have changed lot of things internally, I don't think there are any breaking changes to the public API as such.

**Comment by owenpearson** [comment]
OK as long as there are no breaking changes then it's cool to release this as a patch version 👍 I still think the changelog entries here are very unhelpful and misleading, for example I would change "integration/2.0" to "Upgrade library to protocol v2" (it would be good to change the actual PR title too). Also I think we should remove changes to the README and CI tests from the changelog since these aren't relevant to library users.

**Comment by sacOO7** [comment]
> OK as long as there are no breaking changes then it's cool to release this as a patch version 👍 I still think the changelog entries here are very unhelpful and misleading, for example I would change "integration/2.0" to "Upgrade library to protocol v2" (it would be good to change the actual PR title too). Also I think we should remove changes to the README and CI tests from the changelog since these aren't relevant to library users.

Updated!

**Review by owenpearson — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
