### PR TITLE
Token changes

### PR DESCRIPTION
**Pull request by yavor87**
Fixes Issue #4

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@marto83 would you mind reviewing when you have a chance?  I will do my best now as well.  To understand the context, please see https://github.com/ably/ably-dotnet/issues/4

**Comment by mattheworiordan** [comment]
Largely this looks good other than a few inconsistencies I have spotted. :+1: @yavor87

**Comment by yavor87** [comment]
It is possible that here and there are inconsistencies, but I am not very familiar with the code. That's why I issued the PR so that @mattheworiordan, @marto83 and other team members can check the API and comment on it. Thanks :)

**Comment by mattheworiordan** [comment]
Of course, that's what PRs are for!

**Comment by mattheworiordan** [comment]
@yavor87 is this mergable?

**Comment by mattheworiordan** [comment]
@yavor87 what is the status on this PR?

**Comment by yavor87** [comment]
@mattheworiordan @marto83 There are a few tests that are still failing, but except for that its mergeable and works :)

**Comment by mattheworiordan** [comment]
@yavor87 I am going to close this as it looks like all of these commits are included in https://github.com/ably/ably-dotnet/pull/13.  If this is not the case please shout so I can correct.

**Comment by yavor87** [comment]
@mattheworiordan True, I merged the changed in this branch to the RealtimeClient.

**Pull request closed without merging**
