### PR TITLE
Test and ci improvements

### PR DESCRIPTION
**Pull request by withakay**
I have made some tweaks to tests, mainly allowing some intermittent test to retry and I have added a Circle CI config that will run the tests with dotnet core 2 on linux

### CODE REVIEW

**Comment by funkyboy** [comment]
@withakay Good. Will we see test results on GitHub?

**Comment by withakay** [comment]
@funkyboy Not right away, I don't have the required GitHub permissions on this repo to integrate it.

**Comment by funkyboy** [comment]
@tomczoink I don't either :( 
Better pinging @SimonWoolf or @mattheworiordan

**Comment by SimonWoolf** [comment]
@withakay I've made you a temporary admin of this repo, ping me if you need anything else

**Comment by withakay** [comment]
@SimonWoolf Thanks

**Comment by withakay** [comment]
@funkyboy I now have the permissions I need, but there is not much point setting it up until the outstanding PRs are merged and I had happy that the tests are running OK.

**Comment by funkyboy** [comment]
@withakay Fine by me. Without this, I guess you can't set up the integration :)

**Comment by mattheworiordan** [comment]
Thanks @withakay. Good progress 👏

**Pull request merged**
