### PR TITLE
Network changed events

### PR DESCRIPTION
**Pull request by withakay**
This PR is a solution to the issues raised in #331 and #332.

Regarding #332, I have added sleep/resume handling as if that were a network outage to the .NET Framework (see src/IO.Ably.NETFramework/Platform.cs below).

Instinctively I feel like this shouldn't be required for the client lib to resume from a system sleep but without it when a (Windows) system comes back from sleep the connection doesn't recover. So, perhaps this is a bit of a hack but it makes the library work as expected, so the pragmatist in me says that is OK.

It is possible that similar solutions could be added for iOS and Android, but right now I am not sure what the best options are and no one is complaining of having issues with Xamarin in that regard and testing those solutions is harder, I prefer to push that to another work item.

I should probably have split this up into 2 PRs, but the changes are quite small so hopefully whoever reviews this can overlook that slight faux pas!

### CODE REVIEW

**Comment by withakay** [comment]
I do have a couple of concerns with this PR. 

Firstly, this solution means we get different behaviours on different platforms and even different behaviours on the same platforms depending on how the library is consumed, which is not great. 

Secondly, there is no solution for .NET Standard and this is now the preferred way to consume the library when using Xamarin and .NET Core. At some point in the not too distant future the Android and iOS versions will become legacy.

It might be better to expose hooks and have users wire up the events for each platform themselves

**Comment by withakay** [comment]
@paddybyers 
> How much testing have you been able to do with various network conditions?

I have tested in simulators and a Windows VM, so... not enough.

Is there a provision in the spec for enabling experimental features, perhaps via ClientOptions, because I am confident the solution here does resolve a customer issue on Windows but less confident about the impact on other platforms (specifically Xamarin), so allowing them to enable that might give us some extra breathing room to come up with a more complete solution, WDYT?

**Comment by paddybyers** [comment]
> Is there a provision in the spec for enabling experimental features, perhaps via ClientOptions, because I am confident the solution here does resolve a customer issue on Windows but less confident about the impact on other platforms (specifically Xamarin), so allowing them to enable that might give us some extra breathing room to come up with a more complete solution, WDYT?

I'd be open to enabling a custom client option if we're really not able to establish the stabilty/correctness of this ourselves. I can't help thinking that we're going to need to bite the bullet sooner or later and do the implementation/testing for platform powerstate and network events on the other platforms.

@mattheworiordan wdyt?

**Comment by mattheworiordan** [comment]
> I'd be open to enabling a custom client option if we're really not able to establish the stabilty/correctness of this ourselves. 

Sure, nothing wrong with that, so long as it's undocumented from official docs and has an indicator that it's an experiemental API in the IDE intellisense stuff

**Comment by withakay** [comment]
merging for planned 1.17-beta release

**Pull request merged**
