### PR TITLE
Issue/434 cleanup

### LINKED ISSUE #434: [Cleanup] Remove unused/unnecessary tools and files
- As mentioned in https://github.com/ably/ably-dotnet/pull/431#issuecomment-668086709, there is a lot of unused stuff that can be removed 
- Also https://github.com/ably/ably-dotnet/pull/431#issuecomment-668089332
- Remove unused projects like RealtimeChat from TestHelpers

### PR DESCRIPTION
**Pull request by marto83**
Clean up of unused files

Closes #434

### CODE REVIEW

**Comment by sacOO7** [comment]
Wow, so much cleanup 🙏. Will look into it tomorrow 👍

**Comment by sacOO7** [comment]
Nice cleanup :) Btw, are we not removing NuGet.exe and  ILRepack.exe?

**Comment by marto83** [comment]
I removed nuget but realised the build script was using it and ilrepack is needed for the publish step. So after I removed them I had to add them back in :)

**Comment by sacOO7** [comment]
> I removed nuget but realised the build script was using it and ilrepack is needed for the publish step. So after I removed them I had to add them back in :)

Btw, just a thought, can't we automate it using chocolaty? I am not sure if it will work :p. I don't generally go with targetted binaries to process builds and package management.

**Comment by marto83** [comment]
I'm happy if you would like to automate it with chocolatey.

**Review by sacOO7 — APPROVED** [review]

**Comment by QuintinWillison** [comment]
I have not got enough context to have strong opinions on this PR, but given Martin and Sachin are happy then let's get it merged.

**Pull request merged**
